### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by reziprok** [entepe85/decofill#1]
I just found your polyfill for the CSS property box-decoration-break. Great and thanks for that!
Unfortunately I can't get it to work and it throws: **Uncaught ReferenceError: exports is not defined**

Is it a bug or am I just using it incorrectly? I am not using typescript.

**Comment by entepe85** [comment]
Hey, sorry for the late reply. Did you import the JS as a module?
E.g.: `import { decoFill } from 'decofill'`

And btw: I think I'll have to update the README as it's no longer correct concerning the use of the script. 😅

**Comment by entepe85** [comment]
Please review the current project README for the polyfill's usage alongside a module bundler like webpack or with native ES6 imports.
